// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX-hHwrPsIfY4WGrZ2wgXeAZf5KWe18Ls',
    appId: '1:1079633969142:web:a051ce8850c8645365d1d7',
    messagingSenderId: '1079633969142',
    projectId: 'lualaba-konnect',
    authDomain: 'lualaba-konnect.firebaseapp.com',
    storageBucket: 'lualaba-konnect.firebasestorage.app',
    measurementId: 'G-Y6HJTVSWHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpZ6xdcQJTR5HA7H3uU1MWbs3IcRj9VBg',
    appId: '1:1079633969142:android:3830852cc04bc06465d1d7',
    messagingSenderId: '1079633969142',
    projectId: 'lualaba-konnect',
    storageBucket: 'lualaba-konnect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6wj9JARAG7NauF_ntGqQp_1mJKD0vEDA',
    appId: '1:1079633969142:ios:bb55989b6a2e205665d1d7',
    messagingSenderId: '1079633969142',
    projectId: 'lualaba-konnect',
    storageBucket: 'lualaba-konnect.firebasestorage.app',
    iosBundleId: 'com.example.lualabaKonnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6wj9JARAG7NauF_ntGqQp_1mJKD0vEDA',
    appId: '1:1079633969142:ios:bb55989b6a2e205665d1d7',
    messagingSenderId: '1079633969142',
    projectId: 'lualaba-konnect',
    storageBucket: 'lualaba-konnect.firebasestorage.app',
    iosBundleId: 'com.example.lualabaKonnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX-hHwrPsIfY4WGrZ2wgXeAZf5KWe18Ls',
    appId: '1:1079633969142:web:e7a97ccd681a9db065d1d7',
    messagingSenderId: '1079633969142',
    projectId: 'lualaba-konnect',
    authDomain: 'lualaba-konnect.firebaseapp.com',
    storageBucket: 'lualaba-konnect.firebasestorage.app',
    measurementId: 'G-54343PM2LR',
  );
}
