name: Build Flutter Android Production

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-android-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.5"
          channel: stable
          cache: true

      - name: Show Flutter version
        run: flutter --version

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Build production APK (release)
        run: flutter build apk --release

      - name: Build production AAB (release)
        run: flutter build appbundle --release

      - name: Upload production APK
        uses: actions/upload-artifact@v4
        with:
          name: lualaba-konnect-apk-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload production AAB
        uses: actions/upload-artifact@v4
        with:
          name: lualaba-konnect-aab-release
          path: build/app/outputs/bundle/release/app-release.aab
